{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.phuongtran",
    "module": "android-outbox",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.8.aar",
          "url": "android-outbox-1.3.8.aar",
          "size": 147740,
          "sha512": "31836433b29fef9fa870ff68566bfbb7a1c749e554e434f22c69c6052e98a68284de3bda325967e315f14ed90c09b3a0911efc7bb5d5954ee43b43870ed45cc9",
          "sha256": "341ba4f1c7c9b5b70b1a403b608e5169314e266f4505c42c491fe4c4dfa16d47",
          "sha1": "63ac91832355a698cd15dd00189def5aafded12d",
          "md5": "c931ebd1ca19b50a287d549888506266"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.8.aar",
          "url": "android-outbox-1.3.8.aar",
          "size": 147740,
          "sha512": "31836433b29fef9fa870ff68566bfbb7a1c749e554e434f22c69c6052e98a68284de3bda325967e315f14ed90c09b3a0911efc7bb5d5954ee43b43870ed45cc9",
          "sha256": "341ba4f1c7c9b5b70b1a403b608e5169314e266f4505c42c491fe4c4dfa16d47",
          "sha1": "63ac91832355a698cd15dd00189def5aafded12d",
          "md5": "c931ebd1ca19b50a287d549888506266"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-outbox-1.3.8-sources.jar",
          "url": "android-outbox-1.3.8-sources.jar",
          "size": 24149,
          "sha512": "462dff81284bd84a938de1f8459c6b4544d2ea6f46bf3b8ab332080af43522dfb19a26f1d2f7aa17cd3b8b2807ec281f9e38c47afa1e9acf917b346eadaf1de0",
          "sha256": "44fa39775d52a0b23894a80165e7c789b137e65feb4d53dc995d07d689f8caa9",
          "sha1": "20fc070c8de17d100b6a0f3c4d3b8ccb280a53d2",
          "md5": "7d3d7077cf809b72b1a7535d4eccd830"
        }
      ]
    }
  ]
}
