{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.phuongtran",
    "module": "android-outbox",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.8.aar",
          "url": "android-outbox-1.3.8.aar",
          "size": 147595,
          "sha512": "f7fba1011ff839e2d575ba79c778ae676b4eba117a57b42cbcd18993e6f4a1227909c8c2bfdf40f3d6a396d263a7891d8b0e4c58e10fad5fd0ac6aa10aa7651e",
          "sha256": "0d875a0a5e5304182ce532173740fa1847c711d53bfa7673614ec7dba1a265ce",
          "sha1": "14dc516637b3bc8e34d852e6b190df290ab2dfcd",
          "md5": "955e903461bcd2622a2a70117d75d727"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.8.aar",
          "url": "android-outbox-1.3.8.aar",
          "size": 147595,
          "sha512": "f7fba1011ff839e2d575ba79c778ae676b4eba117a57b42cbcd18993e6f4a1227909c8c2bfdf40f3d6a396d263a7891d8b0e4c58e10fad5fd0ac6aa10aa7651e",
          "sha256": "0d875a0a5e5304182ce532173740fa1847c711d53bfa7673614ec7dba1a265ce",
          "sha1": "14dc516637b3bc8e34d852e6b190df290ab2dfcd",
          "md5": "955e903461bcd2622a2a70117d75d727"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-outbox-1.3.8-sources.jar",
          "url": "android-outbox-1.3.8-sources.jar",
          "size": 24013,
          "sha512": "be45a5f5d1bf7873ea7a56afdc8100e2be215f47e7539349b6a75933f3f434dc9b123f69890d81b76015e399dc5ea0092c2814f1dc9b1cd874e49eb9d7e32c7b",
          "sha256": "a69993c90b8d2c3fcfbfd801e24d6dd89bce7659243a264151de815f49ec1c2c",
          "sha1": "c03ae8ebf22af962f96466d5c943e14975cafd34",
          "md5": "21a70d6d8aa27eb51377fcbdffac5968"
        }
      ]
    }
  ]
}
