{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.phuongtran",
    "module": "android-outbox",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.1.aar",
          "url": "android-outbox-1.3.1.aar",
          "size": 125298,
          "sha512": "4161e190190a57f948bc151fb613f621cdbc33bfb97bea4056c5b10aff45c9d1af5a7ddebbddce56247fcf2929361e768625269a18a9a5b02637334d16598169",
          "sha256": "d1580698b124fb9f8026aafa458b8e300ba4d765ab3fa235d855c179050dd4d6",
          "sha1": "d01123fd0360ca7bb83089cb1d8c368b76f113a8",
          "md5": "3d359275aaf9fd141e8f9905799bcb2b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.1.aar",
          "url": "android-outbox-1.3.1.aar",
          "size": 125298,
          "sha512": "4161e190190a57f948bc151fb613f621cdbc33bfb97bea4056c5b10aff45c9d1af5a7ddebbddce56247fcf2929361e768625269a18a9a5b02637334d16598169",
          "sha256": "d1580698b124fb9f8026aafa458b8e300ba4d765ab3fa235d855c179050dd4d6",
          "sha1": "d01123fd0360ca7bb83089cb1d8c368b76f113a8",
          "md5": "3d359275aaf9fd141e8f9905799bcb2b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-outbox-1.3.1-sources.jar",
          "url": "android-outbox-1.3.1-sources.jar",
          "size": 20457,
          "sha512": "901ad5f7655c44a5a0802461f610870812bbd9ccff53a04181b61685fd9475adc87ae1182d44e449c175b50536ad67d858e095c8d827c5342a11a9c82e30125d",
          "sha256": "c22e6c0e710d8b82bfb69d0202d3ce3146906837e3418eb8b17304217112a011",
          "sha1": "9bfe8bf82b8db42ae1d711a291cbee1fd104fb5c",
          "md5": "c4a975e680c1c2d51b448beedf91dca7"
        }
      ]
    }
  ]
}
