{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.phuongtran",
    "module": "android-outbox",
    "version": "1.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.9.aar",
          "url": "android-outbox-1.3.9.aar",
          "size": 148694,
          "sha512": "5b79366f5e9f6128c2955f009a21a8569b2c805029b3b6e9daa1afcb23df2366658dab5c959510bf8ad752aa1dbfb9fccce19ca28b932b4c817b651ad9ef9b5e",
          "sha256": "cc1850188ff588e682aa9daa9454d6b5f38c685b4013cf34048b7765c4abe54a",
          "sha1": "df8b899709345e6c461b264e834e4acbeb69fa59",
          "md5": "c668095f88643adae193ded954329e86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.9.aar",
          "url": "android-outbox-1.3.9.aar",
          "size": 148694,
          "sha512": "5b79366f5e9f6128c2955f009a21a8569b2c805029b3b6e9daa1afcb23df2366658dab5c959510bf8ad752aa1dbfb9fccce19ca28b932b4c817b651ad9ef9b5e",
          "sha256": "cc1850188ff588e682aa9daa9454d6b5f38c685b4013cf34048b7765c4abe54a",
          "sha1": "df8b899709345e6c461b264e834e4acbeb69fa59",
          "md5": "c668095f88643adae193ded954329e86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-outbox-1.3.9-sources.jar",
          "url": "android-outbox-1.3.9-sources.jar",
          "size": 24701,
          "sha512": "cf8e0f475b6a3936a2ecfa4cc9686eb65d5449ff0e8640fa80c4d6abbd88f2bfd7bbdfab0b2d97a517cf83d9110e8f7255886d1245f09238a265df9b105318a7",
          "sha256": "dfc078112ebab6a5ccf6e517087de6fe75cc7bb6bdee10a4d2b3946762c90678",
          "sha1": "49ee1b7f0744694c55b1fddfa5d7463325446d62",
          "md5": "f036b3bfbcb08f7a2b9507a0c199c802"
        }
      ]
    }
  ]
}
