{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.phuongtran",
    "module": "android-outbox",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.5.aar",
          "url": "android-outbox-1.3.5.aar",
          "size": 142939,
          "sha512": "9a7d3374ff9c60f1f7ebf30279c31b661e05034828b968026fb8e5327b8a6285983673c913efcd1c9a560a0de7f18c92b1ec31fab7d2334507c35efaa204809a",
          "sha256": "d0f7a5e61fd6c4ddca44a880409cfdc187a3e278e63ee7dc5f49d8408851aa68",
          "sha1": "87eb09a1a04723ecca6fc2a548062936e26f1f8b",
          "md5": "e6404226c36aec79c8a1c6f349f2022b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-outbox-1.3.5.aar",
          "url": "android-outbox-1.3.5.aar",
          "size": 142939,
          "sha512": "9a7d3374ff9c60f1f7ebf30279c31b661e05034828b968026fb8e5327b8a6285983673c913efcd1c9a560a0de7f18c92b1ec31fab7d2334507c35efaa204809a",
          "sha256": "d0f7a5e61fd6c4ddca44a880409cfdc187a3e278e63ee7dc5f49d8408851aa68",
          "sha1": "87eb09a1a04723ecca6fc2a548062936e26f1f8b",
          "md5": "e6404226c36aec79c8a1c6f349f2022b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-outbox-1.3.5-sources.jar",
          "url": "android-outbox-1.3.5-sources.jar",
          "size": 23511,
          "sha512": "b24cd57feaf951c6fc684d37ce4221278fc2e7f8fe2de7f23ddeb6ad15c3aad801b783ab83f55593d90f8873c3786a363fe1e7b940e87c46c092c7e8800b0f62",
          "sha256": "315193b72c5ecd3f6cedd3942f1a2e26a040afbec0fea6d28f5fa8f024a4d250",
          "sha1": "6febdfec5a3ab8864c10e1e73c18bda40a0bbba2",
          "md5": "f30fc89e44b6aaa0af842a8290df6913"
        }
      ]
    }
  ]
}
